<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    ''                                                                             => '',
    'Cancel'                                                                       => 'Abbrechen',
    'Create'                                                                       => 'Erstellen',
    'Data'                                                                         => 'Daten',
    'Delete'                                                                       => 'Löschen',
    'Do you want to delete this item?'                                             => 'Wollen Sie diesen Eintrag löschen?',
    'Fields with <span class="required">*</span> are required.'                    => 'Felder mit <span class="required">*</span> sind Pflichtfelder.',
    'Invalid request. Please do not repeat this request again.'                    => 'Ungültige Anfrage. Bitte wiederholen Sie diese Anfrage nicht.',
    'Manage'                                                                       => 'Verwalten',
    'Relations'                                                                    => 'Verknüpfungen',
    'Save'                                                                         => 'Speichern',
    'Search'                                                                       => 'Suche',
    'Switch to view mode to edit related records.'                                 => 'Wechseln Sie in den Ansichtsmodus, um verknüpfte Datensätze zu bearbeiten.',
    'The requested page does not exist.'                                           => 'Die angeforderte Seite existiert nicht.',
    'Update'                                                                       => 'Aktualisieren',
    'View'                                                                         => 'Ansicht',
    'Source Language'                                                              => 'Quell Sprache',
    'Target Language'                                                              => 'Ziel Sprache',
    'Source Page ID'                                                               => 'Zu kopierende Seite',
    'Target Parent Page ID'                                                        => 'Kopie plazieren unter',
    'Required'                                                                     => 'Erforderlich',
    'The complete page was copied successfuly. You can now edit the page.'         => 'Die komplette Seite wurde erfolgreich kopiert. Du kannst die neue Seite nun bearbeiten.',
    'Something went wrong...'                                                      => 'Da lief etwas schief...',
    'No parent pages availible to append a copy.'                                  => 'Keine Seiten verfügbar an die du eine Seitenkopie anhängen kannst/darfst!',
    'Please choose another target language!'                                       => 'Bitte wähle eine andere Ziel Sprache!',
    'Source page could not be found!'                                              => 'Quellseite konnte nicht gefunden werden!',
    'P3Widgets module not availible!'                                              => 'P3Widgets Modul nicht installiert oder nicht verfügbar!',
    'Copy'                                                                         => 'Kopieren',
    'Copy Page'                                                                    => 'Seite kopieren',
    'Step 1 : Select a language from which you want to copy a page'                => 'Schritt 1 : Wähle eine Sprache aus der du eine Seite kopieren möchtest',
    'Step 2 : Select the source page you want to copy'                             => 'Schritt 2 : Wähle die Seite die du kopieren möchtest',
    'Step 3 : Select a P3 parent page to put the copied page below this P3Page ID' => 'Schritt 3 : Wähle eine Stelle im Seitenbaum, unter die die neue Seite kopiert werden soll',
    'Step 4 : Start copy process'                                                  => 'Schritt 4 : Starte den Kopierprozess',
    'Step 5 : Edit the new page'                                                   => 'Schritt 5 : Neue Seite bearbeiten',
);
