<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Ancestor Guid' => '',
  'Begin' => '',
  'Cancel' => '',
  'Check Access Create' => '',
  'Check Access Delete' => '',
  'Check Access Read' => '',
  'Check Access Update' => '',
  'Create' => '',
  'Created At' => '',
  'Created By' => '',
  'Custom Data' => '',
  'Delete' => '',
  'Description' => '',
  'Details ' => '',
  'End' => '',
  'Fields with' => '',
  'Guid' => '',
  'ID' => '',
  'Id0' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Keywords' => '',
  'Label' => '',
  'Language' => '',
  'Layout' => '',
  'Manage' => '',
  'Menu Name' => '',
  'Meta Data' => '',
  'Model' => '',
  'Modified At' => '',
  'Modified By' => '',
  'Owner' => '',
  'P3 Page' => '',
  'P3 Page Meta' => '',
  'P3 Page Metas' => '',
  'P3 Page Translation' => '',
  'P3 Page Translations' => '',
  'P3 Pages' => '',
  'P3Page' => '',
  'P3PageMeta' => '',
  'Page Title' => '',
  'Route' => '',
  'Save' => '',
  'Search' => '',
  'Seo Url' => '',
  'Status' => '',
  'Template' => '',
  'The requested page does not exist.' => '',
  'Tree Parent' => '',
  'Tree Position' => '',
  'TreeParent' => '',
  'Type' => '',
  'Update' => '',
  'View' => '',
  'are required' => '',
  'help.ancestor_guid' => '',
  'help.begin' => '',
  'help.checkAccessCreate' => '',
  'help.checkAccessDelete' => '',
  'help.checkAccessRead' => '',
  'help.checkAccessUpdate' => '',
  'help.createdAt' => '',
  'help.createdBy' => '',
  'help.customData' => '',
  'help.description' => '',
  'help.end' => '',
  'help.guid' => '',
  'help.keywords' => '',
  'help.label' => '',
  'help.language' => '',
  'help.layout' => '',
  'help.menuName' => '',
  'help.model' => '',
  'help.modifiedAt' => '',
  'help.modifiedBy' => '',
  'help.owner' => '',
  'help.pageTitle' => '',
  'help.route' => '',
  'help.seoUrl' => '',
  'help.status' => '',
  'help.treePosition' => '',
  'help.type' => '',
  'help.view' => '',
);
