<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Ancestor Guid' => '',
  'Begin' => 'Anfang',
  'Cancel' => 'Abbrechen',
  'Check Access Create' => 'Erstellen',
  'Check Access Delete' => 'Löschen',
  'Check Access Read' => 'Lesen',
  'Check Access Update' => 'Aktualisieren',
  'Create' => 'Erstellen',
  'Created At' => 'Erstellt am',
  'Created By' => 'Erstellt von',
  'Custom Data' => 'Benutzerdefinierte Daten',
  'Delete' => 'Löschen',
  'Description' => 'Beschreibung',
  'Details ' => '',
  'End' => 'Ende',
  'Fields with' => '',
  'Guid' => '',
  'ID' => '',
  'Id0' => '',
  'Invalid request. Please do not repeat this request again.' => 'Ungültige Anfrage. Bitte wiederholen Sie diese Anfrage nicht.',
  'Keywords' => 'Schlüsselwörter',
  'Label' => 'Bezeichnung',
  'Language' => 'Sprache',
  'Layout' => '',
  'Manage' => 'Verwalten',
  'Menu Name' => 'Menüname',
  'Meta Data' => '',
  'Model' => 'Modell',
  'Modified At' => 'Geändert am',
  'Modified By' => 'Geändert von',
  'Owner' => 'Eigentümer',
  'P3 Page' => '',
  'P3 Page Meta' => '',
  'P3 Page Metas' => '',
  'P3 Page Translation' => '',
  'P3 Page Translations' => '',
  'P3 Pages' => '',
  'P3Page' => '',
  'P3PageMeta' => '',
  'Page Title' => 'Seitentitel',
  'Route' => '',
  'Save' => 'Speichern',
  'Search' => 'Suchen',
  'Seo Url' => '',
  'Status' => '',
  'Template' => '',
  'The requested page does not exist.' => 'Die angeforderte Seite ist nicht vorhanden.',
  'Tree Parent' => '',
  'Tree Position' => '',
  'TreeParent' => '',
  'Type' => '',
  'Update' => 'Aktualisieren',
  'View' => '',
  'are required' => '',
  'help.ancestor_guid' => '',
  'help.begin' => '',
  'help.checkAccessCreate' => '',
  'help.checkAccessDelete' => '',
  'help.checkAccessRead' => '',
  'help.checkAccessUpdate' => '',
  'help.createdAt' => '',
  'help.createdBy' => '',
  'help.customData' => '',
  'help.description' => '',
  'help.end' => '',
  'help.guid' => '',
  'help.keywords' => '',
  'help.label' => '',
  'help.language' => '',
  'help.layout' => 'Layout Rahmen für den u.a. "View"',
  'help.nameId' => '',
  'help.menuName' => '',
  'help.model' => '',
  'help.modifiedAt' => '',
  'help.modifiedBy' => '',
  'help.owner' => '',
  'help.pageTitle' => '',
  'help.route' => 'Konfiguration für Weiterleitungen, wenn angegeben haben diese Werte Vorrang vor "View and Layout"<br/>interne Weiterleitung <code>{"route":"/site/index","params":{"foo":"bar"}}</code><br/>externer Link <code>{"url":"http://example.com"}</code>',
  'help.seoUrl' => '',
  'help.status' => '',
  'help.treePosition' => '',
  'help.type' => '',
  'help.view' => 'Template der Seite, Hinweis: Wenn angegeben hat die "Route" Vorrang vor diesen Werten',
);
