<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Url Param'                                                                       => '',
    'tooltip.created_at'                                                              => '',
    'tooltip.description'                                                             => '',
    'tooltip.id'                                                                      => '',
    'tooltip.keywords'                                                                => '',
    'tooltip.language'                                                                => '',
    'tooltip.menu_name'                                                               => '',
    'tooltip.p3_page_id'                                                              => '',
    'tooltip.page_title'                                                              => '',
    'tooltip.status'                                                                  => '',
    'tooltip.updated_at'                                                              => '',
    'tooltip.url_param'                                                               => '',
    'SEO URL must only contain lowercase characters, numbers, underscores and dashes' => '@@SEO-URL darf nur Kleinbuchstaben, Ziffern, Unterstriche und Bindestriche enthalten@@',
    'Access Append'                                                                   => 'Anfügen',
    'Access Delete'                                                                   => 'Löschen',
    'Access Domain'                                                                   => 'Domain',
    'Access Owner'                                                                    => 'Eigentümer',
    'Access Read'                                                                     => 'Lesen',
    'Access Update'                                                                   => 'Aktualisieren',
    'Copied From'                                                                     => 'Kopiert von',
    'Created At'                                                                      => 'Erstellt am',
    'Custom Data Json'                                                                => 'Daten',
    'Default Description'                                                             => 'Beschreibung',
    'Default Keywords'                                                                => 'Schlüsselwörter',
    'Default Menu Name'                                                               => 'Menü-Name',
    'Default Page Title'                                                              => 'Seitentitel',
    'Default Url Param'                                                               => 'URL Parameter',
    'Description'                                                                     => 'Beschreibung',
    'ID'                                                                              => 'ID',
    'Keywords'                                                                        => 'Schlüsselwörter',
    'Language'                                                                        => 'Sprache',
    'Layout'                                                                          => 'Layout',
    'Menu Name'                                                                       => 'Menü-Name',
    'Name'                                                                            => 'Name (Identifier)',
    'P3 Page'                                                                         => 'Seite',
    'P3 Page Translation'                                                             => 'Seitenübersetzung',
    'P3 Page Translations'                                                            => 'Seitenübersetzungen',
    'P3 Pages'                                                                        => 'Seiten',
    'Page Title'                                                                      => 'Seitentitel',
    'Status'                                                                          => 'Status',
    'Tree Parent'                                                                     => 'Übergeordnete Seite',
    'Tree Position'                                                                   => 'Position',
    'Updated At'                                                                      => 'Aktualisiert am',
    'Url Json'                                                                        => 'Weiterleitung',
    'View'                                                                            => 'Ansicht',
    'relation.P3Page'                                                                 => 'Basisdatensatz',
    'relation.P3PageTranslations'                                                     => 'Übersetzungen',
    'relation.P3Pages'                                                                => 'Unterseiten',
    'relation.TreeParent'                                                             => 'Elternseite',
    'tooltip.access_append'                                                           => 'Rolle, welche das Recht besitzt Unterseiten unter dieser Seite anzulegen.',
    'tooltip.access_delete'                                                           => 'Rolle, welche das Recht besitzt diese Seite zu löschen.',
    'tooltip.access_domain'                                                           => 'Zugriffseinschränkung über die Anwendungssprache.',
    'tooltip.access_owner'                                                            => 'Besitzer dieses Datensatzes.',
    'tooltip.access_read'                                                             => 'Rolle, welche das Recht besitzt diese Seite zu lesen/aufzurufen.',
    'tooltip.access_update'                                                           => 'Rolle, welche das Recht besitzt diese Seite zu aktualisieren.',
    'tooltip.copied_from_id'                                                          => 'Datensatz-ID von welcher dieser Datensatz kopiert wurde.',
    'tooltip.custom_data_json'                                                        => 'Datenbereich für zusätzliche Informationen.',
    'tooltip.default_description'                                                     => 'Inhalt für den HTML-Meta Tag "description" der Seite.',
    'tooltip.default_keywords'                                                        => 'Inhalt für den HTML-Meta Tag "keywords" der Seite.',
    'tooltip.default_menu_name'                                                       => 'Anzeigter Name im Menü.',
    'tooltip.default_page_title'                                                      => 'Seitentitel in der Browserleiste.',
    'tooltip.default_url_param'                                                       => 'Titel zur Verwendung in URL-Regeln.',
    'tooltip.layout'                                                                  => 'Layout-Datei der Seite (i.d.r //layouts/main.php).',
    'tooltip.name_id'                                                                 => 'Name-ID, z.B. zur Verwendung in der Navigationsauswahl "Navbar".',
    'tooltip.tree_parent_id'                                                          => 'Übergeordnete Seite.',
    'tooltip.tree_position'                                                           => 'Position dieser Seite innnerhalb der Seiten der übergeordneten Seite',
    'tooltip.url_json'                                                                => 'Konfiguration für Weiterleitungen, wenn angegeben haben diese Werte Vorrang vor "View und Layout"<br/>interne Weiterleitung <code>{"route":"/site/index","params":{"foo":"bar"}}</code><br/>externer Link <code>{"url":"http://example.com"}</code>',
    'tooltip.view'                                                                    => 'Template der Seite, Hinweis: Wenn angegeben hat die "Route" Vorrang vor diesen Werten',
);
