<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Advanced Search' => '',
  'Cancel' => '',
  'Clear' => '',
  'Clear Search' => '',
  'Copy' => '',
  'Copy Page' => '',
  'Create' => '',
  'Data' => '',
  'Delete' => '',
  'Do you want to delete this item?' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Layout & View' => '',
  'Manage' => '',
  'New Copy Page' => '',
  'No parent pages availible to append a copy.' => '',
  'Please choose another target language!' => '',
  'Relations' => '',
  'Required' => '',
  'Save' => '',
  'Search' => '',
  'Select language' => '',
  'Select source page' => '',
  'Select target parent' => '',
  'Something went wrong...' => '',
  'Source Language' => '',
  'Source Page ID' => '',
  'Step 1' => '',
  'Step 1 : Select a language from which you want to copy a page' => '',
  'Step 2' => '',
  'Step 2 : Select the source page you want to copy' => '',
  'Step 3' => '',
  'Step 3 : Select a P3 parent page to put the copied page below this P3Page ID' => '',
  'Step 4' => '',
  'Step 4 : Start copy process' => '',
  'Step 5' => '',
  'Step 5 : Edit the new page' => '',
  'Switch to view mode to edit related records.' => '',
  'Target Language' => '',
  'Target Parent Page ID' => '',
  'The complete page was copied successfuly. You can now edit the page.' => '',
  'The requested page does not exist.' => '',
  'Update' => '',
  'Update Page' => '',
  'Update Translation' => '',
  'View' => '',
  'View Mode' => '',
);
