<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access Append' => '',
  'Access Delete' => '',
  'Access Domain' => '',
  'Access Owner' => '',
  'Access Read' => '',
  'Access Update' => '',
  'Copied From' => '',
  'Created At' => '',
  'Custom Data Json' => '',
  'Default Description' => '',
  'Default Keywords' => '',
  'Default Menu Name' => '',
  'Default Page Title' => '',
  'Default Url Param' => '',
  'Description' => '',
  'ID' => '',
  'Keywords' => '',
  'Language' => '',
  'Layout' => '',
  'Menu Name' => '',
  'Name' => '',
  'P3 Page' => '',
  'P3 Page Translation' => '',
  'P3 Page Translations' => '',
  'P3 Pages' => '',
  'Page Title' => '',
  'Status' => '',
  'Tree Parent' => '',
  'Tree Position' => '',
  'Updated At' => '',
  'Url Json' => '',
  'Url Param' => '',
  'View' => '',
  'relation.P3Page' => '',
  'relation.P3PageTranslations' => '',
  'relation.P3Pages' => '',
  'tooltip.access_append' => '',
  'tooltip.access_delete' => '',
  'tooltip.access_domain' => '',
  'tooltip.access_owner' => '',
  'tooltip.access_read' => '',
  'tooltip.access_update' => '',
  'tooltip.copied_from_id' => '',
  'tooltip.created_at' => '',
  'tooltip.custom_data_json' => '',
  'tooltip.default_description' => '',
  'tooltip.default_keywords' => '',
  'tooltip.default_menu_name' => '',
  'tooltip.default_page_title' => '',
  'tooltip.default_url_param' => '',
  'tooltip.description' => '',
  'tooltip.id' => '',
  'tooltip.keywords' => '',
  'tooltip.language' => '',
  'tooltip.layout' => '',
  'tooltip.menu_name' => '',
  'tooltip.name_id' => '',
  'tooltip.p3_page_id' => '',
  'tooltip.page_title' => '',
  'tooltip.status' => '',
  'tooltip.tree_parent_id' => '',
  'tooltip.tree_position' => '',
  'tooltip.updated_at' => '',
  'tooltip.url_json' => '',
  'tooltip.url_param' => '',
  'tooltip.view' => '',
);
